// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gcyoctvvomlbtffjybtw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdjeW9jdHZ2b21sYnRmZmp5YnR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg0Mzg1OTQsImV4cCI6MjA1NDAxNDU5NH0.VXLnxYc0c5QFEDO3Fm2s1IKV3p7PP_UjlmFrqnqQ1O8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);